### PR TITLE
Rejuvenate log levels (after fix if-statement and inheritance issue for slf4j)

### PR DESCRIPTION
**Pull request by yiming-tang-cs**
We appreciate your previous feedback and it's very helpful! Here's a reissue of https://github.com/eclipse/californium/pull/933 with a new version of our tool.  Again, we'd appreciate any feedback and are willing to make further changes if you wish to incorporate our PR into your project.

Settings
---
We have several analysis settings. We can vary these settings and rerun if you desire. The settings we are using in this pull request are:

- Treat ERROR/WARN levels as a category and not a traditional level, i.e., our tool ignores these log levels.
- Never lower the logging level of logging statements within catch blocks.
- Never lower the logging level of logging statements within if statements.
- Never lower the logging level of logging statements containing certain (important) keywords.
- Never raise the logging level of logging statements without particular keywords in their messages.
- Avoid log wrapping by disregarding logging statements contained in if statements mentioning log levels.

The greatest number of commits from HEAD evaluated: 1000.
The head at the time of analysis was: 785267fc8a2486260e1e65144ebaf6ca1c1ac81b

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by yiming-tang-cs** [comment]
[results.tar.gz](https://github.com/ponder-lab/californium/files/4036262/results.tar.gz)

**Comment by yiming-tang-cs** [comment]
subject | log expression | log level | DOI value | new level
-- | -- | -- | -- | --
californium-core | LOGGER.debug("{}",log) | DEBUG | 0.69641405 | TRACE
californium-core | LOGGER.info("Received {}. Notification: {}",counter,response.advanced()) | INFO | 0.6578984 | TRACE
californium-core | LOGGER.info("using tokens of {} bytes in length",this.tokenSize) | INFO | 0.49121875 | TRACE
californium-osgi | LOGGER.debug("Adding resource [{}]",resource.getName()) | DEBUG | 0.69960153 | TRACE
californium-osgi | LOGGER.debug("Removing resource [{}]",service.getName()) | DEBUG | 0.6990039 | TRACE
californium-proxy | LOGGER.debug("Outgoing http response: {}",httpResponse.getStatusLine()) | DEBUG | 0.69229686 | TRACE
californium-proxy | LOGGER.debug("Incoming response translated correctly") | DEBUG | 4.887125 | TRACE
californium-proxy | LOGGER.debug("Incoming request translated correctly") | DEBUG | 3.4851913 | TRACE
californium-proxy | LOGGER.info("after manageProxyUriRequest: {}",request) | INFO | 6.350379 | TRACE
californium-proxy | LOGGER.info("Chose {} as clientPath",clientPath) | INFO | 0.6945547 | TRACE
californium-proxy | LOGGER.info("Cache returned {}",response) | INFO | 6.350379 | TRACE
californium-proxy | LOGGER.debug("ProxyCoapClientResource received {}",incomingResponse) | DEBUG | 0.6961484 | TRACE
californium-proxy | LOGGER.info("HTTP returned {}",response) | INFO | 2.286379 | TRACE
californium-proxy | LOGGER.info("ProxyEndpoint handles request {}",request) | INFO | 6.350379 | TRACE
californium-proxy | LOGGER.debug("Root request handled") | DEBUG | 0.685457 | TRACE
californium-proxy | LOGGER.debug("Forward CoAP request to ProxyCoap2Coap: {}",exchange.getRequest()) | DEBUG | 0.6853906 | TRACE
californium-proxy | LOGGER.debug("Incoming http response: {}",result.getStatusLine()) | DEBUG | 6.2962146 | TRACE
cf-extplugtest-client | logger.info("{}",line) | INFO | 2.0916326 | TRACE
cf-extplugtest-client | logger.info("------- {} ------------------------------------------------",tag) | INFO | 2.0916326 | TRACE
cf-extplugtest-client | LOGGER.info("client[{}] next change in {} ms, {} observer.",id,interval,observer) | INFO | 7.6826015 | TRACE
cf-extplugtest-client | logger.info("uptime: {} ms, {} processors",TimeUnit.NANOSECONDS.toMillis(uptimeNanos),processors) | INFO | 2.0916326 | TRACE
cf-extplugtest-client | logger.info("gc: {} ms, {} calls",gcTime,gcCount) | INFO | 2.0916326 | TRACE
cf-extplugtest-client | logger.info("{}",line) | INFO | 2.0916326 | TRACE
cf-extplugtest-client | LOGGER.info("Received response: {} {}",response.advanced(),c) | INFO | 8.3791485 | TRACE
cf-extplugtest-client | logger.info("{}, {}, {}",osMxBean.getName(),osMxBean.getVersion(),osMxBean.getArch()) | INFO | 2.0916326 | TRACE
cf-extplugtest-client | logger.info("cpu-time: {} ms (per-processor: {} ms, load: {}%)",TimeUnit.NANOSECONDS.toMillis(alltime),TimeUnit.NANOSECONDS.toMillis(pTime),(pTime * 100) / uptimeNanos) | INFO | 2.0916326 | TRACE
cf-extplugtest-server | LOGGER.info("{}/{}: {} reverse requests, {} overall.",request.getSourceContext().getPeerAddress(),resource,numberOfRequests,overall) | INFO | 1.3930273 | TRACE
cf-extplugtest-server | logger.info("gc: {} ms, {} calls",gcTime,gcCount) | INFO | 0.6937578 | TRACE
cf-extplugtest-server | LOGGER.debug("{}",request) | DEBUG | 1.3930273 | TRACE
cf-extplugtest-server | LOGGER.info("Removed observation for {}",key) | INFO | 2.8515742 | TRACE
cf-extplugtest-server | logger.info("{} processors",processors) | INFO | 0.6937578 | TRACE
cf-extplugtest-server | logger.info("cpu-time: {} ms (per-processor: {} ms)",TimeUnit.NANOSECONDS.toMillis(alltime),TimeUnit.NANOSECONDS.toMillis(pTime)) | INFO | 0.6937578 | TRACE
cf-nat | LOGGER.info("NAT message dropping {}%.",percent) | INFO | 0.69389063 | TRACE
cf-nat | LOGGER.info("NAT backward message dropping {}%.",percent) | INFO | 0.6941562 | TRACE
cf-nat | LOGGER.info("NAT message reordering {}%.",percent) | INFO | 0.69933593 | TRACE
cf-nat | LOGGER.info("NAT forward message dropping {}%.",percent) | INFO | 0.6946211 | TRACE
cf-oscore | LOGGER.info("Auxiliary Request: " + exchange.getRequest().toString()) | INFO | 2.2002072 | TRACE
cf-oscore | LOGGER.info("Original Request: " + exchange.getRequest().toString()) | INFO | 1.3986055 | TRACE
cf-oscore | LOGGER.info("Request: " + exchange.getRequest().toString()) | INFO | 2.2002072 | TRACE
cf-plugtest-checker | LOG.debug("Parsing link resource: {}",path) | DEBUG | 5.935914 | TRACE
element-connector | LOGGER.debug("set {} {} as timeshift",shift,unit) | DEBUG | 0.6693867 | TRACE
element-connector | LOGGER.debug("Found Begin of {}",tag) | DEBUG | 0.68997264 | TRACE
element-connector | LOGGER.debug("add {} {} to timeshift {} ns",delta,unit,timeShiftNanos) | DEBUG | 0.6691211 | TRACE
element-connector | LOGGER.debug("Found End of {}",tag) | DEBUG | 0.68990624 | TRACE
element-connector | LOGGER.info(String.format("--%02d--> %s",counter,message)) | INFO | 0.6565703 | TRACE
element-connector | LOGGER.info("Test {}",description.getMethodName()) | INFO | 0.65603906 | TRACE
element-connector | LOGGER.info("Threads {}: {} threads",message,list.size()) | INFO | 0.67941403 | TRACE
scandium | LOGGER.debug("{}",log) | DEBUG | 0.69953513 | TRACE
scandium | LOGGER.info("{} ranges",ranges.size()) | INFO | 0.53272265 | TRACE
scandium | LOGGER.info(" fragment [{}:{})",msg.getFragmentOffset(),msg.getFragmentOffset() + msg.getFragmentLength()) | INFO | 0.5322578 | TRACE
scandium | LOGGER.debug("certificate chain is signed with supported algorithm(s)") | DEBUG | 0.44659373 | TRACE
scandium | LOG.debug(msg.toString()) | DEBUG | 2.066996 | TRACE
scandium | LOGGER.info("  {}",range) | INFO | 0.53272265 | TRACE
scandium | LOGGER.debug("Indicating max. fragment length [{}] to server [{}]",maxFragmentLengthCode,getPeerAddress()) | DEBUG | 0.50629294 | TRACE
scandium | LOGGER.debug("certificate is NOT signed with supported algorithm(s)") | DEBUG | 0.44666013 | TRACE
scandium | LOG.debug("{}connection: size {}, remaining {}!",tag,connections.size(),remaining) | DEBUG | 0.5011133 | TRACE
californium-proxy | LOGGER.info("HttpStack listening on port {}",httpPort) | INFO | 8.383531 | DEBUG
californium-proxy | LOGGER.info("Received HTTP request and translate to {}",coapRequest) | INFO | 10.483465 | DEBUG
californium-proxy | LOGGER.info("Submitted http listening to thread 'HttpStack listener'") | INFO | 8.383531 | DEBUG

**Comment by saledouble** [comment]
Most of log levels are transformed into `TRACE`.  As shown above, their DOI values are positive. We only consider three log levels  (`TRACE`, `DEBUG` and `INFO`) instead of five log levels. Each DOI interval becomes larger. More log levels are transformed into the lowest log level.

**Comment by yiming-tang-cs** [comment]
Most of the log levels are transformed into `TRACE`.  As shown above, their DOI values are positive. We only consider three log levels  (`TRACE`, `DEBUG` and `INFO`) instead of five log levels. Each DOI interval becomes larger. The percentage of log levels which are transformed into the lowest log level is bigger.

**Comment by khatchad** [comment]
What is "most?" How many are moved to trace? What was their original level? How many are not trace?

**Comment by khatchad** [comment]
Oh I see that https://github.com/ponder-lab/californium/pull/5#issuecomment-572148734 shows this. I didn't see it in the email. It would be better to have a summary of this rather than the unsorted raw data. It's difficult to see how things are changing. It may also be interesting to see larger N.

**Comment by khatchad** [comment]
BTW, your description is not linking the original PR.

**Comment by yiming-tang-cs** [comment]
>Oh I see that #5 (comment) shows this. I didn't see it in the email. It would be better to have a summary of this rather than the unsorted raw data. It's difficult to see how things are changing. It may also be interesting to see larger N.

I will try a larger N and send you a summary.

**Comment by yiming-tang-cs** [comment]
>BTW, your description is not linking the original PR.

I don't want to bother the developers. The developers should be notified if I linked the original PR.

**Comment by khatchad** [comment]
> > BTW, your description is not linking the original PR.
> 
> I don't want to bother the developers. The developers should be notified if I linked the original PR.

I don't think they will be notified and you run the risk of forgetting to link it when you do the real PR.

**Comment by yiming-tang-cs** [comment]
>I don't think they will be notified and you run the risk of forgetting to link it when you do the real PR.

OK. I modified the description.

**Pull request closed without merging**
